import { copy, type LocalCopy } from "./service-content";
type ArticleSection = { heading: LocalCopy; paragraphs: LocalCopy[]; points?: LocalCopy[]; links?: { slug: string; label: LocalCopy }[] };
export const articles: { slug: string; category: "AI Systems" | "Automation" | "Case Studies"; title: LocalCopy; excerpt: LocalCopy; readTime: number; diagram: string[]; sections: ArticleSection[]; takeaway: LocalCopy; service: string }[] = [
  {
    slug: "ai-agent-dan-workflow-automation", category: "AI Systems", readTime: 4,
    title: copy("AI agent dan workflow automation: kapan menggunakan masing-masing?", "AI agents and workflow automation: when should you use each?"),
    excerpt: copy("Pahami peran aturan, konteks, dan tools saat merancang sistem yang benar-benar menjalankan pekerjaan.", "Understand the role of rules, context, and tools when designing systems that actually execute work."),
    diagram: ["Business event", "Rules + AI context", "Tool execution"], service: "ai-agent-systems",
    sections: [
      { heading: copy("Mulai dari pekerjaan, bukan antarmuka", "Start with the work, not the interface"), paragraphs: [copy("Ketika membahas AI untuk bisnis, percakapan sering dimulai dari chatbot. Padahal kebutuhan tim bisa jauh lebih luas: memeriksa dokumen, memperbarui CRM, memprioritaskan tugas, atau menghubungkan data antar aplikasi. Pertanyaan pertama sebaiknya adalah pekerjaan apa yang perlu diselesaikan, bukan tampilan seperti apa yang akan digunakan.", "Business AI discussions often start with chatbots. Yet teams may need to review documents, update a CRM, prioritize tasks, or connect data across applications. The first question should be which work needs doing, rather than which interface to use.")] },
      { heading: copy("Workflow untuk langkah yang jelas", "Workflows for clearly defined steps"), paragraphs: [copy("Workflow automation cocok ketika trigger, aturan, dan tujuan tiap langkah dapat dijelaskan dengan jelas. Misalnya, formulir masuk divalidasi, diperiksa duplikasinya, lalu disimpan ke CRM. Jika data belum lengkap, alur masuk ke antrean pemeriksaan. Percabangannya ditentukan oleh aturan bisnis yang dapat diuji.", "Workflow automation fits processes whose triggers, rules, and outcomes can be clearly specified. For example, a form is validated, checked for duplicates, and saved to a CRM. Incomplete records go to a review queue. Business rules determine branches that can be tested.")] },
      { heading: copy("Agent untuk interpretasi konteks", "Agents for interpreting context"), paragraphs: [copy("Agent dapat menjadi bagian dari sistem ketika suatu tugas membutuhkan pemahaman teks, dokumen, atau konteks yang bervariasi. Agent diberi tujuan serta akses ke tools tertentu. Ruang tindakannya tetap perlu dibatasi: data apa yang boleh dibaca, operasi apa yang boleh dilakukan, dan kapan harus meminta bantuan manusia.", "An agent can be part of a system when a task requires interpreting variable text, documents, or context. It receives a goal and access to specific tools. Its scope still needs boundaries: which data it can read, which operations it can perform, and when to involve a person.")] },
      { heading: copy("Gabungkan keduanya dalam satu proses", "Combine both in one process"), paragraphs: [copy("Bayangkan invoice baru masuk. Workflow menangani penerimaan file dan identitas dokumen. AI mengekstrak informasi. Aturan mencocokkan total dengan purchase order. Hasil yang cocok masuk antrean approval, sementara selisih dibuatkan tugas review. Tidak semua langkah perlu menggunakan AI untuk menghasilkan alur yang berguna.", "Consider a new invoice. A workflow receives the file and identifies the document. AI extracts information. Rules match totals against a purchase order. Matching invoices enter approval, while discrepancies create review tasks. A useful workflow does not need AI in every step.")] },
      { heading: copy("Tentukan kontrol sebelum implementasi", "Define controls before implementation"), paragraphs: [copy("Pisahkan langkah membaca, menyiapkan, dan mengeksekusi tindakan. Gunakan contoh kasus normal dan exception untuk menguji keputusan. Log perlu menjelaskan jalur yang dipilih dan hasil tiap tahap agar tim bisa meninjau masalah saat proses tidak berjalan sesuai harapan.", "Separate reading, preparing, and executing actions. Test decisions with normal cases and exceptions. Logs should explain the selected path and each step's outcome so the team can investigate when a process behaves unexpectedly.")], points: [copy("Tetapkan pemilik proses dan batas kewenangan.", "Assign a process owner and permission boundaries."), copy("Definisikan input, output, dan jalur exception.", "Define inputs, outputs, and exception paths."), copy("Sepakati tindakan yang memerlukan approval.", "Agree which actions need approval.")] },
    ],
    takeaway: copy("Pilih workflow untuk urutan yang jelas, gunakan agent untuk kebutuhan interpretasi, dan satukan keduanya dengan kontrol yang dapat ditinjau tim.", "Use workflows for defined sequences, agents for interpretation, and connect both with controls your team can review."),
  },
  {
    slug: "memilih-proses-pertama-untuk-automasi", category: "Automation", readTime: 4,
    title: copy("Cara memilih proses pertama untuk diotomasi", "How to choose your first process to automate"),
    excerpt: copy("Kerangka sederhana untuk memilih pilot berdasarkan masalah nyata, kesiapan data, dan hasil yang dapat diukur.", "A practical framework for choosing a pilot based on real problems, data readiness, and measurable outcomes."),
    diagram: ["Map the process", "Define a pilot", "Measure & improve"], service: "ai-strategy",
    sections: [
      { heading: copy("Cari pekerjaan yang berulang dan jelas batasnya", "Find repeatable work with clear boundaries"), paragraphs: [copy("Pilot yang baik memiliki awal, akhir, dan pemilik yang dapat ditentukan. Mulai dengan satu proses yang bisa dijelaskan tim: memindahkan lead dari formulir ke CRM, merapikan laporan rutin, atau memeriksa data invoice. Hindari memasukkan semua pekerjaan satu departemen ke tahap pertama.", "A useful pilot has a defined beginning, end, and owner. Start with one process the team can describe: moving form leads into a CRM, preparing routine reports, or checking invoice data. Keep the first stage focused rather than covering an entire department.")] },
      { heading: copy("Petakan kondisi awal", "Map the baseline"), paragraphs: [copy("Catat langkah yang dilakukan sekarang, siapa yang mengerjakannya, aplikasi yang digunakan, serta tempat proses sering tertahan. Gunakan contoh data nyata yang diizinkan untuk diperiksa. Perhatikan kasus yang tidak mengikuti alur normal karena exception sering menentukan kebutuhan review dan desain integrasi.", "Document current steps, owners, applications, and common bottlenecks. Use real examples that you are allowed to review. Pay attention to cases outside the normal flow, since exceptions often shape review requirements and integration design.")], points: [copy("Apa trigger yang memulai pekerjaan?", "What event starts the work?"), copy("Data apa yang dibutuhkan setiap langkah?", "What data does each step require?"), copy("Siapa yang menangani kegagalan atau ketidakjelasan?", "Who handles failures or ambiguity?")] },
      { heading: copy("Periksa kesiapan data dan akses", "Check data and access readiness"), paragraphs: [copy("Sebelum memilih tools, periksa apakah sumber data tersedia dan formatnya cukup konsisten. Tinjau akses API, hak pengguna, dan batas integrasi aplikasi yang terlibat. Jika data masih tersebar atau tidak memiliki pemilik, merapikan sumber tersebut dapat menjadi bagian dari pilot.", "Before choosing tools, check whether source data is available and reasonably consistent. Review API access, user permissions, and integration constraints. If data is scattered or has no owner, organizing it may be part of the pilot.")] },
      { heading: copy("Sepakati ukuran keberhasilan", "Agree on success measures"), paragraphs: [copy("Tentukan ukuran yang sesuai dengan masalah awal. Jika kendalanya perpindahan data manual, ukur waktu proses dan kebutuhan koreksi. Jika masalahnya pekerjaan yang terlewat, periksa kelengkapan tugas dan jumlah exception. Catat kondisi awal supaya hasil pilot memiliki pembanding yang jelas.", "Choose measures that match the initial problem. For manual data transfers, track processing time and corrections. For missed work, examine task completeness and exception volume. Record a baseline so the pilot has a clear comparison.")] },
      { heading: copy("Mulai kecil, lalu perluas berdasarkan hasil", "Start small and expand based on results"), paragraphs: [copy("Batasi jenis input, aplikasi, dan tindakan untuk tahap awal. Jalankan dengan data contoh, lalu uji bersama pemilik proses. Tentukan siapa yang memantau, bagaimana alur dihentikan, dan apa langkah pemulihan jika terjadi error. Perluasan dilakukan setelah tim memahami hasil dan batas sistem.", "Limit input types, applications, and actions in the initial stage. Start with sample data, then test with the process owner. Define monitoring, how to stop the workflow, and recovery steps for errors. Expand once the team understands the system's results and limits.")] },
    ],
    takeaway: copy("Pilot yang terarah menjawab satu masalah nyata, memiliki data yang siap, dan dinilai dengan ukuran keberhasilan yang disepakati sebelum dibangun.", "A focused pilot addresses one real problem, has usable data, and is evaluated against measures agreed before implementation."),
  },
  {
    slug: "alur-invoice-dengan-approval", category: "Case Studies", readTime: 4,
    title: copy("Merancang alur invoice dengan validasi dan approval", "Designing an invoice workflow with validation and approval"),
    excerpt: copy("Contoh rancangan proses dari dokumen masuk hingga draft ERP, termasuk jalur ketika nilai invoice tidak sesuai.", "An example process from incoming documents to ERP drafts, including the path for mismatched invoice amounts."),
    diagram: ["Extract invoice", "Match purchase order", "Review / ERP draft"], service: "workflow-automation",
    sections: [
      { heading: copy("Sebuah contoh rancangan, bukan hasil proyek klien", "An illustrative design, not a client project result"), paragraphs: [copy("Contoh ini menunjukkan bagaimana pemrosesan dokumen dapat digabungkan dengan aturan bisnis dan review finance. Tujuannya menyiapkan data untuk keputusan tim, dengan membedakan hasil ekstraksi, validasi, dan persetujuan. Cakupan sebenarnya perlu mengikuti sistem dan kebijakan perusahaan.", "This example shows how document processing can be combined with business rules and finance review. It prepares data for team decisions while distinguishing extraction, validation, and approval. Actual scope needs to follow company systems and policies.")] },
      { heading: copy("Terima dokumen dan ekstrak informasi", "Receive documents and extract information"), paragraphs: [copy("Alur dimulai saat PDF masuk melalui folder atau email yang ditentukan. Simpan referensi dokumen dan identitas event agar proses dapat ditelusuri. Ekstraksi menyiapkan vendor, nomor invoice, tanggal, item, dan total sebagai data terstruktur. Field yang tidak terbaca atau ambigu perlu ditandai untuk review.", "The flow begins when a PDF arrives in a designated folder or inbox. Save document references and event identifiers for traceability. Extraction prepares vendor, invoice number, date, line items, and total as structured records. Unreadable or ambiguous fields should be flagged for review.")] },
      { heading: copy("Validasi dengan data pembanding", "Validate against reference data"), paragraphs: [copy("Periksa kelengkapan informasi dan kemungkinan dokumen duplikat sebelum mencocokkan dengan purchase order. Aturan perlu menjelaskan cara membandingkan item, mata uang, dan total. Toleransi selisih, jika ada, ditentukan oleh pemilik proses finance dan ditulis sebagai aturan yang dapat diuji.", "Check required fields and potential duplicates before matching the purchase order. Rules need to specify how to compare line items, currency, and totals. Any discrepancy tolerance is defined by the finance process owner and recorded as a testable rule.")] },
      { heading: copy("Pisahkan jalur sesuai dan jalur exception", "Separate matched and exception paths"), paragraphs: [copy("Invoice yang sesuai masuk ke antrean persetujuan dengan ringkasan dan referensi sumber. Data dapat disimpan sebagai draft ERP sambil menunggu approval. Jika total berselisih atau PO tidak ditemukan, buat tugas pemeriksaan untuk tim finance. Notifikasi harus menyertakan alasan penahanan agar tim mengetahui tindakan berikutnya.", "Matched invoices enter approval with a summary and source references. Data can be staged as an ERP draft while awaiting approval. A mismatched total or missing PO creates a finance review task. Notifications should include the hold reason so the team knows what to do next.")] },
      { heading: copy("Uji jalur yang jarang terjadi", "Test the less common paths"), paragraphs: [copy("Selain invoice normal, uji dokumen duplikat, field hilang, total berbeda, dan koneksi aplikasi gagal. Tentukan kapan proses mencoba kembali dan kapan perlu intervensi manusia. Status draft, approved, dan posted harus memiliki arti yang jelas agar hasil simulasi tidak disalahartikan sebagai transaksi yang sudah terjadi.", "Alongside normal invoices, test duplicates, missing fields, differing totals, and failed application connections. Define when to retry and when people should intervene. Draft, approved, and posted statuses need clear meanings so a simulation is not mistaken for an executed transaction.")], points: [copy("Simpan referensi dokumen dan hasil validasi.", "Keep document references and validation results."), copy("Tetapkan pemilik antrean exception.", "Assign an exception queue owner."), copy("Pisahkan approval dari posting atau pembayaran.", "Separate approval from posting or payment.")] },
    ],
    takeaway: copy("Automasi invoice yang baik membuat data siap ditinjau, memperjelas exception, dan menjaga titik persetujuan sesuai kebijakan finance.", "A useful invoice workflow prepares reviewable data, makes exceptions clear, and preserves approval checkpoints aligned with finance policy."),
  },
  {
    slug: "automasi-lead-ke-crm", category: "Case Studies", readTime: 3,
    title: copy("Studi alur: dari lead masuk ke CRM dan follow-up", "Workflow study: from incoming leads to CRM and follow-up"),
    excerpt: copy("Ilustrasi automasi sales dengan dua jalur: lead prioritas masuk pipeline, lead tahap awal masuk nurture.", "An illustrative sales automation with two paths: qualified leads enter the pipeline, early-stage leads enter nurture."),
    diagram: ["Capture + enrich", "Qualify lead", "CRM / Nurture"], service: "workflow-automation",
    sections: [
      { heading: copy("Kondisi awal dalam contoh ini", "The starting point in this example"), paragraphs: [copy("Bayangkan tim menerima lead dari formulir website. Data perlu disalin ke CRM, kebutuhan dibaca, dan tindak lanjut dibuat satu per satu. Contoh ini merupakan rancangan ilustratif untuk menunjukkan jalur automasi; bukan laporan hasil proyek klien atau klaim peningkatan konversi.", "Imagine a team receiving website form leads. Records need copying into a CRM, needs need reviewing, and follow-up tasks are created individually. This is an illustrative automation design, not a client project report or a conversion improvement claim.")] },
      { heading: copy("Tangkap dan perkaya profil", "Capture and enrich the profile"), paragraphs: [copy("Saat formulir masuk, workflow memeriksa field wajib dan menormalisasi data. Cari kontak yang sudah ada sebelum membuat record baru. Informasi kebutuhan, ukuran perusahaan, dan waktu implementasi menjadi konteks untuk kualifikasi. Data yang tidak tersedia tetap ditandai sebagai belum diketahui, bukan diisi dengan asumsi.", "When a form arrives, the workflow checks required fields and normalizes data. Look for an existing contact before creating a new record. Needs, company size, and implementation timing provide qualification context. Unavailable data remains marked unknown rather than filled with assumptions.")] },
      { heading: copy("Kualifikasi menjadi dua jalur", "Qualification creates two paths"), paragraphs: [copy("Kriteria kecocokan ditetapkan bersama pemilik proses sales. Dalam contoh ini, lead yang memiliki kebutuhan jelas dan rencana implementasi dekat masuk jalur prioritas. Lead yang masih mengeksplorasi masuk jalur nurture. Jika informasi ambigu, proses dapat membuat tugas review sebelum memilih jalur.", "Fit criteria are agreed with the sales process owner. In this example, a lead with clear needs and near-term implementation enters the priority path. Exploratory leads enter nurture. Ambiguous information can create a review task before a path is selected.")] },
      { heading: copy("Siapkan tindakan sesuai segmen", "Prepare actions for each segment"), paragraphs: [copy("Untuk lead prioritas, workflow membuat atau memperbarui deal, menetapkan pemilik, lalu menyiapkan tugas follow-up. Untuk lead tahap awal, sistem menyimpan konteks dan memilih rangkaian edukasi yang sesuai. Pengiriman komunikasi mengikuti izin kontak serta kebijakan tim; contoh alur ini menggambarkan langkah yang perlu disesuaikan sebelum implementasi.", "For qualified leads, the workflow creates or updates a deal, assigns an owner, and prepares a follow-up task. For early-stage leads, it saves context and selects a relevant educational sequence. Communications follow contact permissions and team policy; this example outlines steps that need adapting before implementation.")] },
      { heading: copy("Hasil yang perlu diperiksa tim", "What the team should review"), paragraphs: [copy("Tinjau apakah record terduplikasi, segmentasi masuk akal, dan tugas diterima pemilik yang benar. Bandingkan waktu penanganan dengan kondisi awal serta periksa lead yang masuk exception. Ukuran keberhasilan ditentukan dari data implementasi, bukan dari angka contoh pada simulasi.", "Review duplicates, segmentation decisions, and whether tasks reach the correct owner. Compare handling time with the baseline and inspect exception leads. Success measures come from implementation data rather than sample numbers in the simulation.")], points: [copy("Satu record lead dengan konteks yang terstruktur.", "One lead record with structured context."), copy("Jalur sales atau nurture yang dapat ditelusuri.", "A traceable sales or nurture path."), copy("Pemilik dan tindakan berikutnya yang jelas.", "A clear owner and next action.")] },
    ],
    takeaway: copy("Automasi sales membantu menyatukan data, memilih jalur penanganan, dan menyiapkan tindak lanjut dengan pemilik yang jelas.", "Sales automation connects data, selects a handling path, and prepares follow-up with clear ownership."),
  },
];

export const pillarSlug = "panduan-ai-automation-untuk-bisnis";
export const blogCategories = [
  { slug: "ai-systems", category: "AI Systems" },
  { slug: "automation", category: "Automation" },
  { slug: "studi-kasus", category: "Case Studies" },
] as const;

articles.unshift({
  slug: pillarSlug, category: "Automation", readTime: 6, service: "workflow-automation",
  title: copy("Panduan AI Automation untuk bisnis: dari proses manual ke sistem terhubung", "AI automation for business: from manual processes to connected systems"),
  excerpt: copy("Mulai dari memilih proses, memahami peran AI, hingga merancang automasi sales dan invoice dengan kontrol tim.", "From choosing a process and understanding AI to designing sales and invoice automation with team controls."),
  diagram: ["Choose a process", "Connect data & apps", "Review & improve"],
  sections: [
    { heading: copy("Apa itu AI Automation untuk bisnis?", "What is AI automation for business?"), paragraphs: [copy("AI Automation menggabungkan pemahaman informasi dengan langkah kerja yang terhubung. AI membantu membaca teks atau dokumen yang bentuknya bervariasi. Workflow mengatur kapan proses dimulai, aturan yang harus dipenuhi, aplikasi yang menerima data, dan siapa yang memeriksa hasilnya.", "AI automation combines understanding information with connected work steps. AI helps read variable text or documents. A workflow defines when work starts, which rules apply, where data goes, and who reviews the outcome."), copy("Contohnya, dokumen dari email dibaca, nilainya diperiksa terhadap pesanan, lalu draft disiapkan untuk tim finance. Manfaat yang ingin diuji adalah berkurangnya perpindahan data manual dan pekerjaan yang terlewat. Hasilnya perlu diukur pada proses Anda sendiri.", "For example, an emailed document is read, checked against an order, and prepared as a draft for finance. The intended benefits to test are less manual data transfer and fewer missed tasks. Results need measuring in your own process.")] },
    { heading: copy("Kapan menggunakan workflow, kapan menggunakan AI agent?", "When should you use workflows or AI agents?"), paragraphs: [copy("Gunakan aturan tetap untuk keputusan yang sudah jelas, seperti field wajib dan pengecekan duplikasi. Gunakan AI ketika informasi perlu diinterpretasikan, misalnya kebutuhan calon pelanggan dalam paragraf bebas. Agent dapat menggunakan tools, tetapi akses dan kewenangannya perlu ditentukan sebelum sistem berjalan.", "Use fixed rules for clear decisions such as required fields and duplicate checks. Use AI when information needs interpreting, such as a prospect's needs in free text. Agents can use tools, but their access and authority need defining before the system runs.")], links: [{ slug: "ai-agent-dan-workflow-automation", label: copy("Pahami perbedaan AI agent dan workflow automation", "Understand AI agents versus workflow automation") }] },
    { heading: copy("Bagaimana memilih proses pertama yang layak diotomasi?", "How do you choose the first process to automate?"), paragraphs: [copy("Pilih pekerjaan berulang dengan awal dan akhir yang jelas. Catat siapa pemiliknya, aplikasi yang dipakai, serta waktu dan koreksi yang dibutuhkan saat ini. Mulai dari satu jenis input dan satu hasil yang bisa diperiksa, lalu uji kasus normal maupun kasus yang memerlukan bantuan tim.", "Choose recurring work with clear boundaries. Record its owner, applications, and current processing time and corrections. Start with one input type and a verifiable outcome, then test routine cases and cases requiring team help.")], links: [{ slug: "memilih-proses-pertama-untuk-automasi", label: copy("Gunakan kerangka memilih pilot automasi pertama", "Use a framework for choosing your first automation pilot") }] },
    { heading: copy("Bagaimana automasi lead masuk ke CRM dan follow-up?", "How can incoming leads connect to CRM and follow-up?"), paragraphs: [copy("Saat formulir diterima, sistem memeriksa kelengkapan, mencari kontak yang sudah ada, lalu menyimpan kebutuhan calon pelanggan. Kriteria bisnis menentukan apakah tim sales perlu segera menindaklanjuti atau calon pelanggan masih membutuhkan informasi. Tugas harus memiliki pemilik agar kontak baru tidak berhenti di spreadsheet.", "When a form arrives, the system checks completeness, looks for an existing contact, and saves the prospect's needs. Business criteria determine whether sales should follow up now or the prospect needs more information. Tasks need owners so new contacts do not stop in a spreadsheet.")], links: [{ slug: "automasi-lead-ke-crm", label: copy("Lihat rancangan alur lead ke CRM dan follow-up", "Explore a lead-to-CRM and follow-up design") }] },
    { heading: copy("Bagaimana automasi invoice tetap memakai persetujuan finance?", "How can invoice automation retain finance approval?"), paragraphs: [copy("Pisahkan membaca dokumen, mencocokkan data, dan memberi persetujuan. Nilai yang sesuai bisa disiapkan sebagai draft, sedangkan selisih harus ditandai untuk pemeriksaan. Persetujuan dan pemrosesan akhir tetap mengikuti kewenangan tim; membaca invoice dengan AI tidak berarti pembayaran otomatis disetujui.", "Separate reading documents, matching data, and approval. Matching values can become drafts, while discrepancies are flagged for review. Approval and final processing follow team authority; reading an invoice with AI does not automatically authorize payment.")], links: [{ slug: "alur-invoice-dengan-approval", label: copy("Pelajari validasi invoice dan jalur persetujuan finance", "Learn about invoice validation and finance approval") }] },
    { heading: copy("Apa yang perlu disiapkan sebelum implementasi?", "What should you prepare before implementation?"), paragraphs: [copy("Siapkan contoh data yang boleh digunakan, panduan proses, dan akses aplikasi yang dibutuhkan. Sepakati langkah yang hanya menyiapkan draft serta tindakan yang memerlukan persetujuan. Tentukan juga cara memantau kegagalan, mengulang pekerjaan tanpa duplikasi, dan menghentikan alur saat diperlukan.", "Prepare permitted data samples, process guidelines, and required application access. Agree which steps only prepare drafts and which actions need approval. Define failure monitoring, retries without duplicates, and how to stop the workflow when needed.")], points: [copy("Pemilik proses dan daftar aplikasi yang terlibat.", "A process owner and a list of involved applications."), copy("Contoh kasus rutin, data tidak lengkap, dan pengecualian.", "Examples of routine cases, incomplete data, and exceptions."), copy("Ukuran awal untuk waktu proses, koreksi, dan kelengkapan tugas.", "Baseline measures for processing time, corrections, and task completeness.")] },
  ],
  takeaway: copy("Mulai dari satu proses yang jelas. Hubungkan data dan aplikasi, gunakan AI pada langkah yang membutuhkan interpretasi, lalu ukur hasilnya bersama pemilik proses.", "Start with a defined process. Connect data and apps, use AI where interpretation is needed, and measure the outcome with the process owner."),
});

// Connect each supporting article to the guide and a relevant next topic.
for (const article of articles.filter(item => item.slug !== pillarSlug)) {
  const nextSlug = article.slug === "alur-invoice-dengan-approval" ? "ai-agent-dan-workflow-automation" : article.slug === "automasi-lead-ke-crm" ? "memilih-proses-pertama-untuk-automasi" : article.slug === "ai-agent-dan-workflow-automation" ? "alur-invoice-dengan-approval" : "automasi-lead-ke-crm";
  const next = articles.find(item => item.slug === nextSlug)!;
  article.sections[article.sections.length - 1].links = [
    { slug: pillarSlug, label: copy("Kembali ke panduan lengkap AI Automation untuk bisnis", "Return to the complete business AI automation guide") },
    { slug: next.slug, label: next.title },
  ];
}
